### ISSUE TITLE
fix conda activate while using direnv

### ISSUE THREAD

**Issue by y1450** [y1450/dotfiles#41]
was using .envrc file for automatic loading of environment but apparently conda doesn't play nice with terminal and show conda shell not intialized error.

**Comment by y1450** [comment]
https://github.com/direnv/direnv/issues/326

**Comment by y1450** [comment]
```
source /ebio/abt3_projects/databases/miniconda3/etc/profile.d/conda.sh
conda activate MY_CONDA_ENV 
``` 
this works

**Comment by wanghaiqiangk** [comment]
Is the PS1 properly changed to reflect conda environment name?

My conda environment name is always the `base` even if a environment with different name has actually been activated.
